language: node_js
services:
    - mongodb
    - redis-server
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "4.1"
  - "0.12"
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 test"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/addon"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/bin"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 test/common"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/common/blob"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/common/core"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/common/storage"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/common/util"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/config"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/issue"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/plugin"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/seeds"
  - "node ./node_modules/mocha/bin/mocha -R dot --timeout 10000 --recursive test/server"
  - "npm run test_browser"
